name: A Different Christmas
favicon: null
layout_spectrum: 0.18972386652603745
typography_spectrum: 0.8906587532255799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.0011710694525390863
  lightness: 0.4389593340456486
  saturation: 0.926094172289595
  rhythmicContrast: 0.4996430024039
purpose: []
